apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "opentelemetry-collector.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "opentelemetry-collector.fullname" . }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config=/etc/otel/collector.yaml"
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: {{ include "opentelemetry-collector.fullname" . }}
