apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-api-config
  labels:
    {{- include "inventory-api.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
