apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "jaeger.fullname" . }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: 4317
    - name: otlp-http
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: 4318
    - name: query
      port: {{ .Values.service.queryPort }}
      targetPort: 16686
